### PR TITLE
Use `uint64` for `GeneralizedIndex`

### PR DESCRIPTION
**Pull request by etan-status**
To support adressing any nimbus-eth2 `BeaconState` member, 32-bit wide
indices are not enough. `BeaconState` requires 5 levels of depth;
`VALIDATOR_REGISTRY_LIMIT` for the `validators` array requires 40 levels
for the contents plus 2 levels for `len` and the root. Another 4 levels
are required for `Validator`. This means that 52-bit indices are needed.
Extending to `uint64` should provide enough leeway without requiring
further implementation adjustments.

### CODE REVIEW

**Comment by etan-status** [comment]
I think that the internal `mergedDataHash` etc which operate on `int64` do not need adjustment, because they only operate on sub-trees where `1.GeneralizedIndex` through `3.GeneralizedIndex` (length) are mapped to array element 0, and `4.GeneralizedIndex` is mapped to element 1 (i.e., two bits are stripped). So, even if a full-width `uint64` index was hypothetically used, this should still work.

**Comment by tersec** [comment]
`nimbus-eth2` doesn't support more than `int32`-allowed validatorindices, regardless. That's arguably an unfortunate implementation detail, but also a bottleneck regardless of this change.

**Comment by etan-status** [comment]
Wait for https://github.com/status-im/nim-ssz-serialization/pull/19 before merging this.

**Comment by etan-status** [comment]
Wait for https://github.com/status-im/nim-ssz-serialization/pull/16 before merging this.

**Pull request merged**
